[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node rapidsnark-sha256-pipeline.cjs --continuous --interval 0"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
NODE_ENV = "production"