[build]
builder = "NIXPACKS"
buildCommand = "chmod +x rapidsnark-prover"

[deploy]
startCommand = "node rapidsnark-sha256-pipeline.cjs --continuous --interval 0"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[volumes]
cache = "/app/cache"

[environments.production]
NODE_ENV = "production"
RAILWAY_VOLUME_MOUNT_PATH = "/app/cache"